### ISSUE TITLE
Replace rust-gmp dependency by rug

### ISSUE THREAD

**Issue by robinhundt** [mikelodder7/unknown_order#6]
As noted in #5 the rust-gmp dependency very likely contains UB by using the deprecated [uninitialized](https://doc.rust-lang.org/std/mem/fn.uninitialized.html) function instead of [MaybeUninit](https://doc.rust-lang.org/std/mem/fn.uninitialized.html).  
rust-gmp does not seem to be maintained with the last commit being in 2017 and 11 open pull requests.  
I propose to replace rust-gmp by [rug](https://crates.io/crates/rug) which is an actively maintained high-level interface to GMP (among others). The major difference is, that it statically links gmp instead of dynamically like rust-gmp. Personally, I see that as an advantage of rug over rust-gmp.

**Comment by mikelodder7** [comment]
Agreed. It's been one of my goals but haven't had the chance to yet. Thanks for bringing this up.

**Comment by mikelodder7** [comment]
Fixed with 47f036c96b39881c9120f5a0ae24cb637a0ddee1
